version: 2.1

orbs:
  platformio-orb: gbusch/platformio-orb@0.3.1

jobs:
  build:
    executor: platformio-orb/default
    steps:
      - checkout
      - platformio-orb/compile
      - platformio-orb/publish
